### ISSUE TITLE
Incorrect output for bytes with values of 128-255

### ISSUE THREAD

**Issue by LukAss741** [nmrugg/LZMA-JS#17]
LZMA-JS doesn't work correctly for bytes with values of 128-255. It returns them as [expected output]-256

It can be easily fixed with:
new LZMA.decompress(input, function (output)
{
	for (var a = 0; a < output.length; a++)
	{
		if (output[a] < 0)
		{
			output[a] += 256;
		}
	}
}

Could it be fixed within lzma_worker.js? Thanks for considering.

**Comment by nmrugg** [comment]
It used to do that. I removed that a little while ago since it's usually 
unnecessary, and it can be converted to whatever type you want with just 
a single line of code. But maybe I'll add an option to convert it 
automatically. I'll think about it. But I don't like adding overhead if 
it can be helped.

If you want to convert it to an unsigned typed array, you can just do this:

output = new Uint8Array(output);

Of if you need it to be a regular JavaScript array, you can just do this:

output = Array.prototype.slice.call(new Uint8Array(output));

**Comment by LukAss741** [comment]
OK that is great. Thanks!

**Comment by LukAss741** [comment]
Hi. output of new LZMA.decompress(input, output); is string in case all values of the output array are between 0 to 127. In case there is at least 1 value of the array greater than 128 then output is an array of numbers.
Is this expected behaviour? In case it is, is there a simple trick to make output treat as an array of numbers in any case?

**Comment by nmrugg** [comment]
Actually, it will correctly handle any non-binary Unicode string even if 
it has values above 127 (for example, it can handle Chinese characters 
just fine). However, when it detects binary data, it returns an array 
because it's (probably) impossible to convert it to a string without 
corrupting the data.

It will always attempt to convert it to a string. There is no option to 
force it to return an array.

Currently, I supposed a simple trick would be to add a null value (i.e., 
0) to the beginning or end of an array. For example [65] will return 
"A", but [65,0] will return [65,0]. That's a pretty hacky though.

If you know that the data is below 128, you could do this:

if (typeof output=== "string") {
     output = output.split("").map(function (s){return s.charCodeAt(0)});
}

If there's enough interest in it, I'll consider adding an option for that.

**Comment by LukAss741** [comment]
The problem is that I use windows 1250 encoding - I obviously want transfered data to be as small as possible and therefore 1 byte per character is alright while unicode with 2 bytes per character is needless wasting of data for my needs.

Now if uncompressed string input is "abcd" then uncompressed byte[] input is [97,98,99,100] then compressed it is [93,0,0,128,0,4,0,0,0,0,0,0,0,0,48,152,136,152,57,150,55,83] then decompressed it is a string "abcd"

If uncompressed input is "ábčď" then uncompressed byte[] input is [225,98,232,239] then compressed it is [93,0,0,128,0,4,0,0,0,0,0,0,0,0,112,152,153,14,248,128,0,0] then decompressed it is a byte[] [-31,98,-24,-17]

Therefore if input contains values of ascii only then output is a string but if it contains at least 1 character outside ascii then output is a byte[].

With if (typeof output === "string") I can workaround it. But I would say it is werid that it returns 2 possible data types. Your consideration.

My problem is now resolved. Thanks for your help!

**Comment by nmrugg** [comment]
I suppose it can be confusing for there to be two different types of 
possible data types to be returned. If there's enough interest in an 
option that always returns an array, I'll consider adding it.

Thanks for the input!

**Comment by LukAss741** [comment]
I just added a byte with value 0 at the end of uncompressed data to make the javascript not crash when uncompressed input was zero length which solved my problem with string as well. Therefore I don't necessairly need it. Thanks for your willingness anyway.
