### ISSUE TITLE
streams

### ISSUE THREAD

**Issue by nickdesaulniers** [nmrugg/LZMA-JS#34]
nice library, I wrote a streams wrapper for it: https://github.com/nickdesaulniers/lzma-stream. Just so you know.

**Comment by addaleax** [comment]
@nickdesaulniers The LZMA compression format does, unfortunately not work that way, i.e. you can’t just concatenate multiple LZMA-encoded buffers and hope for the best. Your one test case works, but that’s more a peculiarity of Node.js streams:
You pass in input that is so small that it fits within a single 64 kB Buffer (which is the chunk size `fs.createReadStream` currently gives you), so you get a single call to `_transform` and therefore a single call to `lzma.compress`. Once the files get so big that you actually make use of streaming, the approach fails and results in a truncated and/or corrupt result.
(NB: With the newer `.xz` format, you actually *can* just concatenate multiple streams, but decompression would still fail.)

Since either way your code is Node.js-specific, I’d suggest you rather use something along the lines of [my lzma-native bindings](https://github.com/addaleax/lzma-native), which has the advantage of being *a lot* faster since it’s native code (About 10× faster than this library using pure JS code, depending on compression options). There are other Node.js bindings to the native `liblzma` available, but all of them use the `.xz` format rather than `.lzma`, like this library.

**Comment by nickdesaulniers** [comment]
oh, nice.  It makes sense that for multiple calls to transform that things would get messed up.  I'll deprecate my project and unpublish from npm.

**Comment by addaleax** [comment]
Ok – maybe this module will come with streams support some time (there has been talk about it, e.g. at #18), but still, I think if you know you’re going to use Node.js, using a native library is a good idea (esp. since LZMA compression is quite slow anyway).

I realize that my docs might not be too clear about it, but if you want to stick to the `.lzma` format, you can use lzma-native like this:

```js
var lzma = require('lzma-native');

// the extra option is necessary for .lzma
var compressor = lzma.createStream('aloneEncoder');
// can accept both .xz and .lzma streams via auto-detection
var decompressor = lzma.createDecompressor();
```

**Comment by nmrugg** [comment]
Thanks for letting us know about your work. I do hope to get streams working in the future, but it's not an extremely easy task.
